spring:
  application:
    name: CulturalEventApplication

  h2:
    console.enabled: true

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

  mail:
    host: smtp.gmail.com
    port: 587
    username: pompaciepla27@gmail.com
    password: Szaranagajama12
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true